imr_classnames = ['goldfish', 'great white shark', 'hammerhead', 'stingray', 'hen', 'ostrich', 'goldfinch', 'junco', 
'bald eagle', 'vulture', 'newt', 'axolotl', 'tree frog', 'iguana', 'African chameleon', 'cobra', 'scorpion', 'tarantula', 
'centipede', 'peacock', 'lorikeet', 'hummingbird', 'toucan', 'duck', 'goose', 'black swan', 'koala', 'jellyfish', 'snail', 
'lobster', 'hermit crab', 'flamingo', 'american egret', 'pelican', 'king penguin', 'grey whale', 'killer whale', 'sea lion', 
'chihuahua', 'shih tzu', 'afghan hound', 'basset hound', 'beagle', 'bloodhound', 'italian greyhound', 'whippet', 'weimaraner', 
'yorkshire terrier', 'boston terrier', 'scottish terrier', 'west highland white terrier', 'golden retriever', 'labrador retriever',
'cocker spaniels', 'collie', 'border collie', 'rottweiler', 'german shepherd dog', 'boxer', 'french bulldog', 'saint bernard',
'husky', 'dalmatian', 'pug', 'pomeranian', 'chow chow', 'pembroke welsh corgi', 'toy poodle', 'standard poodle', 'timber wolf',
'hyena', 'red fox', 'tabby cat', 'leopard', 'snow leopard', 'lion', 'tiger', 'cheetah', 'polar bear', 'meerkat', 'ladybug',
'fly', 'bee', 'ant', 'grasshopper', 'cockroach', 'mantis', 'dragonfly', 'monarch butterfly', 'starfish', 'wood rabbit',
'porcupine', 'fox squirrel', 'beaver', 'guinea pig', 'zebra', 'pig', 'hippopotamus', 'bison', 'gazelle', 'llama', 'skunk',
'badger', 'orangutan', 'gorilla', 'chimpanzee', 'gibbon', 'baboon', 'panda', 'eel', 'clown fish', 'puffer fish', 'accordion',
'ambulance', 'assault rifle', 'backpack', 'barn', 'wheelbarrow', 'basketball', 'bathtub', 'lighthouse', 'beer glass',
'binoculars', 'birdhouse', 'bow tie', 'broom', 'bucket', 'cauldron', 'candle', 'cannon', 'canoe', 'carousel', 'castle',
'mobile phone', 'cowboy hat', 'electric guitar', 'fire engine', 'flute', 'gasmask', 'grand piano', 'guillotine', 'hammer',
'harmonica', 'harp', 'hatchet', 'jeep', 'joystick', 'lab coat', 'lawn mower', 'lipstick', 'mailbox', 'missile', 'mitten',
'parachute', 'pickup truck', 'pirate ship', 'revolver', 'rugby ball', 'sandal', 'saxophone', 'school bus', 'schooner',
'shield', 'soccer ball', 'space shuttle', 'spider web', 'steam locomotive', 'scarf', 'submarine', 'tank', 'tennis ball',
'tractor', 'trombone', 'vase', 'violin', 'military aircraft', 'wine bottle', 'ice cream', 'bagel', 'pretzel',
'cheeseburger', 'hotdog', 'cabbage', 'broccoli', 'cucumber', 'bell pepper', 'mushroom', 'Granny Smith', 'strawberry',
'lemon', 'pineapple', 'banana', 'pomegranate', 'pizza', 'burrito', 'espresso', 'volcano', 'baseball player',
'scuba diver', 'acorn']
